[versions]
projectVersion = "0.2.1-SNAPSHOT"
minJava = "17"

[libraries]
jackson = "com.fasterxml.jackson.core:jackson-databind:2.21.1"
assertj = "org.assertj:assertj-core:4.0.0-M1"
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.13.0-RC1"
spockframework = "org.spockframework:spock-bom:2.4-M6-groovy-3.0"

[plugins]
gradle-publish = "com.gradle.plugin-publish:2.0.0"
spotless = "com.diffplug.spotless:8.2.1"
